x-smc-common:
  &smc-common
  build:
    context: .
    args:
      USERNAME: $USER
      UID: ${USER_ID:-0}
      GID: ${GROUP_ID:-0}
  volumes:
    - .:/app
    - smc-gems:/gems
    - /app/node_modules
  stdin_open: true # docker run -i
  tty: true        # docker run -t
  environment:
    DB_DEV: smc-development
    DB_HOST: db
    DB_TEST: smc-test
    DB_USERNAME: postgres
    GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    REDIS_URL: redis://redis:6379
    XERO_ID: ${XERO_ID}
    XERO_SECRET: ${XERO_SECRET}


services:
  web:
    << : *smc-common
    command: "./script/start-dev.sh"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:11.5
    volumes:
      - smc-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

  sidekiq:
    << : *smc-common
    command: bundle exec sidekiq -r . -C config/sidekiq.yml
    depends_on:
      - db
      - redis
      - web

volumes:
  smc-data:
  smc-gems:
